//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Ibp_Cab
    {
        public int id_Ibp_Cab { get; set; }
        public Nullable<int> id_Empresa { get; set; }
        public Nullable<int> id_TipoDoc { get; set; }
        public Nullable<System.DateTime> fechaSolicitud { get; set; }
        public string nro_Documento { get; set; }
        public string apellidos_Peronal { get; set; }
        public string nombre_personal { get; set; }
        public Nullable<int> estado { get; set; }
        public Nullable<int> usuario_creacion { get; set; }
        public Nullable<System.DateTime> fecha_creacion { get; set; }
        public Nullable<int> usuario_edicion { get; set; }
        public Nullable<System.DateTime> fecha_edicion { get; set; }
    }
}
